# Inventory Demand Forecasting - Data Cleaning
## RetailMart Inc. - Machine Learning Project

---

### Objective
This notebook focuses on **data loading, quality assessment, and cleaning** for the inventory demand forecasting project.

### Datasets
- `fact_sales.csv` - Daily sales transactions
- `dim_products.csv` - Product master data
- `dim_stores.csv` - Store information
- `dim_dates.csv` - Calendar with holidays and seasons
- `dim_suppliers.csv` - Supplier reliability and lead times

---

## 1. Import Libraries

In [25]:
# Core libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', None)

print("Libraries imported successfully!")

Libraries imported successfully!

---
## 2. Task 1.1: Data Loading & Initial Assessment

### 2.1 Load All CSV Files

In [26]:
# Define data path
DATA_PATH = 'data/'

# Load all datasets
fact_sales = pd.read_csv(f'{DATA_PATH}fact_sales.csv')
dim_products = pd.read_csv(f'{DATA_PATH}dim_products.csv')
dim_stores = pd.read_csv(f'{DATA_PATH}dim_stores.csv')
dim_dates = pd.read_csv(f'{DATA_PATH}dim_dates.csv')
dim_suppliers = pd.read_csv(f'{DATA_PATH}dim_suppliers.csv')

print("All datasets loaded successfully!")
print(f"\nDataset Shapes:")
print(f"   • fact_sales: {fact_sales.shape}")
print(f"   • dim_products: {dim_products.shape}")
print(f"   • dim_stores: {dim_stores.shape}")
print(f"   • dim_dates: {dim_dates.shape}")
print(f"   • dim_suppliers: {dim_suppliers.shape}")

All datasets loaded successfully!

Dataset Shapes:
   • fact_sales: (47371, 15)
   • dim_products: (210, 10)
   • dim_stores: (52, 10)
   • dim_dates: (731, 14)
   • dim_suppliers: (20, 10)

### 2.2 Explore Fact Sales Table

In [27]:
print("=" * 60)
print("FACT_SALES TABLE")
print("=" * 60)
print(f"\nShape: {fact_sales.shape}")
print(f"\nColumn Data Types:")
print(fact_sales.dtypes)
print(f"\nFirst 5 Rows:")
fact_sales.head()

============================================================
FACT_SALES TABLE
============================================================

Shape: (47371, 15)

Column Data Types:
transaction_id          object
date_id                 object
product_id              object
store_id                object
quantity_sold          float64
unit_price             float64
gross_amount           float64
discount_percentage      int64
discount_amount        float64
net_amount             float64
is_promotion            object
current_stock_level    float64
reorder_point            int64
units_to_stock           int64
stockout_flag            int64
dtype: object

First 5 Rows:

,transaction_id,date_id,product_id,store_id,quantity_sold,unit_price,gross_amount,discount_percentage,discount_amount,net_amount,is_promotion,current_stock_level,reorder_point,units_to_stock,stockout_flag
0,T100001,2023-01-01,P1026,ST021,2.0,NaN,536.90,0,0.0,536.90,No,282.0,31,0,0
1,T100002,2023-01-01,P1191,ST011,1.0,86.06,86.06,0,0.0,86.06,No,190.0,65,0,0
2,T100003,2023-01-01,P1143,ST018,4.0,236.75,947.00,0,0.0,947.00,No,469.0,70,0,0
3,T100004,2023-01-01,P1110,ST020,20.0,19.37,387.40,0,0.0,387.40,No,287.0,36,0,0
4,T100005,2023-01-01,P1111,ST010,19.0,23.62,448.78,0,0.0,448.78,No,172.0,28,0,0

In [28]:
# Check for missing values in fact_sales
print("Missing Values in fact_sales:")
missing_sales = fact_sales.isnull().sum()
missing_pct = (missing_sales / len(fact_sales) * 100).round(2)
missing_df = pd.DataFrame({'Missing Count': missing_sales, 'Percentage (%)': missing_pct})
print(missing_df[missing_df['Missing Count'] > 0])

Missing Values in fact_sales:
                     Missing Count  Percentage (%)
quantity_sold                  896            1.89
unit_price                    1425            3.01
gross_amount                   955            2.02
net_amount                     965            2.04
current_stock_level           2218            4.68

### 2.3 Explore Dimension Tables

In [29]:
print("=" * 60)
print("DIM_PRODUCTS TABLE")
print("=" * 60)
print(f"Shape: {dim_products.shape}")
print(f"\nData Types:\n{dim_products.dtypes}")
print(f"\nFirst 5 Rows:")
dim_products.head()

============================================================
DIM_PRODUCTS TABLE
============================================================
Shape: (210, 10)

Data Types:
product_id          object
product_name        object
category            object
subcategory         object
unit_price         float64
cost_price         float64
supplier_id         object
shelf_life_days    float64
weight_kg          float64
is_perishable       object
dtype: object

First 5 Rows:

,product_id,product_name,category,subcategory,unit_price,cost_price,supplier_id,shelf_life_days,weight_kg,is_perishable
0,P1001,Smartphones Item 1,ELECTRONICS,Smartphones,1049.28,451.98,S118,NaN,6.39,No
1,P1002,Smartphones Item 2,Elctronics,Smartphones,287.25,176.60,S118,NaN,6.79,No
2,P1003,Smartphones Item 3,Electronics,Smartphones,597.74,314.88,S109,NaN,14.36,No
3,P1004,Smartphones Item 4,Electronics,Smartphones,670.74,321.52,S102,NaN,8.09,No
4,P1005,Smartphones Item 5,Electronics,Smartphones,1466.39,858.65,S112,NaN,10.60,No

In [30]:
# Check unique categories - identify typos
print("Unique Categories (with typos):")
print(dim_products['category'].unique())

Unique Categories (with typos):
['ELECTRONICS' 'Elctronics' 'Electronics' 'electronics' 'Electroncs'
 'Clothing' 'CLOTHING' 'clothing' 'Clothng' 'Groceries' 'groceries'
 'Grocereis' 'GROCERIES' 'Grocery' 'Home & Kitchen' 'Home and Kitchen'
 'home & kitchen' 'Home&Kitchen' 'HOME & KITCHEN' 'Beauty' 'Beauti'
 'BEAUTY' 'beauty']

In [31]:
print("=" * 60)
print("DIM_STORES TABLE")
print("=" * 60)
print(f"Shape: {dim_stores.shape}")
print(f"\nData Types:\n{dim_stores.dtypes}")
print(f"\nFirst 5 Rows:")
dim_stores.head()

============================================================
DIM_STORES TABLE
============================================================
Shape: (52, 10)

Data Types:
store_id             object
store_name           object
store_type           object
city                 object
region               object
store_size_sqft       int64
opening_date         object
manager_id           object
num_employees       float64
parking_capacity      int64
dtype: object

First 5 Rows:

,store_id,store_name,store_type,city,region,store_size_sqft,opening_date,manager_id,num_employees,parking_capacity
0,ST001,Chicago Warehouse #5,Warehouse,Chicago,North,22797,2018-10-20,M1036,56.0,151
1,ST002,Chicago Hypermarket #1,NaN,Chicago,North,15614,2020-04-24,M1034,175.0,313
2,ST003,Detroit Hypermarket #5,Hypermarket,Detroit,N,17588,2020-09-18,M1035,164.0,203
3,ST004,Minneapolis Supermarket #5,Supermarket,Minneapolis,N,4662,2015-04-20,M1039,187.0,450
4,ST005,Minneapolis Express #2,Express,Minneapolis,North,1783,2019-04-07,M1010,82.0,11

In [32]:
# Check unique regions - identify inconsistencies
print("Unique Regions (with inconsistencies):")
print(dim_stores['region'].unique())

Unique Regions (with inconsistencies):
['North' 'N' 'north' 'South' 'S' 'SOUTH' 'East' 'E' 'EAST' 'West' 'WEST'
 'W' 'Central' 'C']

In [33]:
print("=" * 60)
print("DIM_DATES TABLE")
print("=" * 60)
print(f"Shape: {dim_dates.shape}")
print(f"\nData Types:\n{dim_dates.dtypes}")
print(f"\nFirst 5 Rows:")
dim_dates.head()

============================================================
DIM_DATES TABLE
============================================================
Shape: (731, 14)

Data Types:
date_id         object
date_display    object
year             int64
month            int64
month_name      object
day              int64
day_of_week      int64
day_name        object
week_of_year     int64
quarter         object
season          object
is_weekend       int64
is_holiday       int64
is_month_end     int64
dtype: object

First 5 Rows:

,date_id,date_display,year,month,month_name,day,day_of_week,day_name,week_of_year,quarter,season,is_weekend,is_holiday,is_month_end
0,2023-01-01,2023-01-01,2023,1,Jan,1,6,Sunday,52,Q1,Winter,1,1,0
1,2023-01-02,2023/01/02,2023,1,January,2,0,Monday,1,1,Winter,0,0,0
2,2023-01-03,2023-01-03,2023,1,January,3,1,Tuesday,1,Q1,Winter,0,0,0
3,2023-01-04,2023-01-04,2023,1,January,4,2,Wednesday,1,Q1,Winter,0,0,0
4,2023-01-05,2023-01-05,2023,1,January,5,3,Thursday,1,Q1,Winter,0,0,0

In [34]:
print("=" * 60)
print(" DIM_SUPPLIERS TABLE")
print("=" * 60)
print(f"Shape: {dim_suppliers.shape}")
print(f"\n Data Types:\n{dim_suppliers.dtypes}")
print(f"\n All Rows:")
dim_suppliers

============================================================
 DIM_SUPPLIERS TABLE
============================================================
Shape: (20, 10)

 Data Types:
supplier_id            object
supplier_name          object
contact_email          object
phone                  object
country                object
lead_time_days        float64
reliability_score     float64
min_order_quantity      int64
payment_terms          object
active_status          object
dtype: object

 All Rows:

,supplier_id,supplier_name,contact_email,phone,country,lead_time_days,reliability_score,min_order_quantity,payment_terms,active_status
0,S101,GLOBAL SUPPLIES CO,contact@globalsupp.com,+1-389-119-6965,Mexico,5.0,4.1,100,Net 60,Yes
1,S102,FastTrack Logistics,contact@fasttrackl.com,+1-619-756-6276,China,24.0,NaN,25,Net 60,active
2,S103,Prime Distributors,contact@primedistr.com,NaN,Vietnam,19.0,4.2,10,Net 15,Active
3,S104,QUALITY FIRST INC,contact@qualityfir.com,+1-281-579-1994,Japan,16.0,4.6,10,NaN,Active
4,S105,Reliable Wholesale,contact@reliablewh.com,NaN,Mexico,6.0,3.5,100,Net 60,active
5,S106,Express Shipping Ltd,contact@expressshi.com,+1-771-525-2728,Japan,25.0,4.8,25,Net 60,1
6,S107,MegaMart Suppliers,contact@megamartsu.com,+1-653-460-6163,Japan,16.0,3.9,500,Net 15,1
7,S108,Value Chain Partners,contact@valuechain.com,+1-962-360-6898,Canada,15.0,NaN,10,Net 15,1
8,S109,Direct Source Inc,contact@directsour.com,NaN,Mexico,13.0,NaN,500,Net 15,1
9,S110,Premium Goods LLC,contact@premiumgoo.com,+1-238-571-6827,India,14.0,3.5,50,Net 15,Yes
10,S111,Swift Delivery Co,contact@swiftdeliv.com,NaN,Japan,8.0,4.8,500,NaN,Active
11,S112,Trusted Vendors Inc,contact@trustedven.com,+1-790-490-2285,USA,13.0,4.6,100,Net 30,active
12,S113,Alliance Distribution,contact@alliancedi.com,+1-849-896-7266,USA,4.0,4.1,50,NaN,active
13,S114,Core Supplies Ltd,contact@coresuppli.com,+1-656-870-9269,China,12.0,3.3,50,Net 30,Active
14,S115,United Wholesalers,contact@unitedwhol.com,+1-644-892-3136,India,9.0,4.3,25,NaN,1
15,S116,Star Logistics,NaN,+1-531-801-2467,China,16.0,3.4,50,NaN,ACTIVE
16,S117,Elite Distributors,contact@elitedistr.com,+1-652-738-3389,Canada,NaN,3.4,50,Net 60,Active
17,S118,First Choice Suppliers,NaN,+1-351-989-5713,USA,28.0,3.9,10,Net 15,1
18,S119,Rapid Response Inc,contact@rapidrespo.com,+1-761-594-3315,USA,24.0,3.5,10,Net 15,1
19,S120,Efficient Supply Co,contact@efficients.com,+1-268-497-5445,Japan,3.0,4.8,100,Net 60,1

### 2.4 Document Data Quality Issues

In [35]:
print("=" * 70)
print("DATA QUALITY ISSUES SUMMARY")
print("=" * 70)

issues = {
    'fact_sales': [
        'Missing values in quantity_sold, unit_price, current_stock_level',
        'Inconsistent date formats in date_id',
        'Outliers in quantity_sold (values > 100)',
        'Duplicate transaction records',
        'Inconsistent casing in product_id and store_id'
    ],
    'dim_products': [
        'Typos in category (Electroncs, Clothng, Grocereis, Beuty)',
        'Inconsistent casing (ELECTRONICS, electronics, Electronics)',
        'Missing values in subcategory, unit_price, weight_kg',
        'Duplicate product records'
    ],
    'dim_stores': [
        'Inconsistent region naming (NORTH, north, Northern, N)',
        'Missing values in store_size_sqft, num_employees',
        'Duplicate store records'
    ],
    'dim_dates': [
        'Mixed date formats in date_display',
        'Inconsistent quarter format (Q1 vs 1)',
        'Abbreviated vs full month names'
    ],
    'dim_suppliers': [
        'Inconsistent active_status (Active, active, ACTIVE, Yes, 1)',
        'Missing values in contact_email, lead_time_days, reliability_score',
        'Phone shows N/A for missing values'
    ]
}

for table, issue_list in issues.items():
    print(f"\n {table.upper()}:")
    for i, issue in enumerate(issue_list, 1):
        print(f"   {i}. {issue}")

======================================================================
DATA QUALITY ISSUES SUMMARY
======================================================================

 FACT_SALES:
   1. Missing values in quantity_sold, unit_price, current_stock_level
   2. Inconsistent date formats in date_id
   3. Outliers in quantity_sold (values > 100)
   4. Duplicate transaction records
   5. Inconsistent casing in product_id and store_id

 DIM_PRODUCTS:
   1. Typos in category (Electroncs, Clothng, Grocereis, Beuty)
   2. Inconsistent casing (ELECTRONICS, electronics, Electronics)
   3. Missing values in subcategory, unit_price, weight_kg
   4. Duplicate product records

 DIM_STORES:
   1. Inconsistent region naming (NORTH, north, Northern, N)
   2. Missing values in store_size_sqft, num_employees
   3. Duplicate store records

 DIM_DATES:
   1. Mixed date formats in date_display
   2. Inconsistent quarter format (Q1 vs 1)
   3. Abbreviated vs full month names

 DIM_SUPPLIERS:
   1. Inconsistent active_status (Active, active, ACTIVE, Yes, 1)
   2. Missing values in contact_email, lead_time_days, reliability_score
   3. Phone shows N/A for missing values

---
## 3. Task 1.2: Data Cleaning

### 3.1 Clean dim_products

In [36]:
# Create a copy for cleaning
products_clean = dim_products.copy()

# Step 1: Standardize product_id to uppercase
products_clean['product_id'] = products_clean['product_id'].str.upper().str.strip()

# Step 2: Fix category typos and standardize casing
category_mapping = {
    'electroncs': 'Electronics', 'electronics': 'Electronics', 'ELECTRONICS': 'Electronics',
    'clothng': 'Clothing', 'clothing': 'Clothing', 'CLOTHING': 'Clothing',
    'grocereis': 'Groceries', 'groceries': 'Groceries', 'GROCERIES': 'Groceries',
    'home&kitchen': 'Home & Kitchen', 'home & kitchen': 'Home & Kitchen', 
    'HOME & KITCHEN': 'Home & Kitchen', 'Home&Kitchen': 'Home & Kitchen',
    'beuty': 'Beauty', 'beauty': 'Beauty', 'BEAUTY': 'Beauty', 'beauti': 'Beauty'
}

# Apply mapping (case-insensitive)
products_clean['category'] = products_clean['category'].str.strip().str.lower()
products_clean['category'] = products_clean['category'].replace({
    'electroncs': 'electronics', 'clothng': 'clothing', 
    'grocereis': 'groceries', 'beuty': 'beauty', 'beauti': 'beauty',
    'home&kitchen': 'home & kitchen'
})
products_clean['category'] = products_clean['category'].str.title()
products_clean['category'] = products_clean['category'].replace({'Home & Kitchen': 'Home & Kitchen'})

# Step 3: Handle missing values
products_clean['subcategory'] = products_clean['subcategory'].fillna('Unknown')
products_clean['unit_price'] = products_clean['unit_price'].fillna(products_clean['unit_price'].median())
products_clean['weight_kg'] = products_clean['weight_kg'].fillna(products_clean['weight_kg'].median())

# Step 4: Remove duplicates
print(f"Before removing duplicates: {len(products_clean)} rows")
products_clean = products_clean.drop_duplicates(subset=['product_id'], keep='first')
print(f"After removing duplicates: {len(products_clean)} rows")

print("\ndim_products cleaned!")
print(f"\nUnique categories now: {products_clean['category'].unique()}")

Before removing duplicates: 210 rows
After removing duplicates: 200 rows

dim_products cleaned!

Unique categories now: ['Electronics' 'Elctronics' 'Clothing' 'Groceries' 'Grocery'
 'Home & Kitchen' 'Home And Kitchen' 'Beauty']

### 3.2 Clean dim_stores

In [37]:
# Create a copy for cleaning
stores_clean = dim_stores.copy()

# Step 1: Standardize store_id to uppercase
stores_clean['store_id'] = stores_clean['store_id'].str.upper().str.strip()

# Step 2: Standardize region names
region_mapping = {
    'north': 'North', 'NORTH': 'North', 'n': 'North', 'N': 'North', 'northern': 'North',
    'south': 'South', 'SOUTH': 'South', 's': 'South', 'S': 'South', 'southern': 'South',
    'east': 'East', 'EAST': 'East', 'e': 'East', 'E': 'East', 'eastern': 'East',
    'west': 'West', 'WEST': 'West', 'w': 'West', 'W': 'West', 'western': 'West',
    'central': 'Central', 'CENTRAL': 'Central', 'c': 'Central', 'C': 'Central'
}
stores_clean['region'] = stores_clean['region'].str.strip().replace(region_mapping)

# Step 3: Handle missing values
stores_clean['store_size_sqft'] = stores_clean['store_size_sqft'].fillna(
    stores_clean['store_size_sqft'].median()
)
stores_clean['num_employees'] = stores_clean['num_employees'].fillna(
    stores_clean['num_employees'].median()
)
stores_clean['store_type'] = stores_clean['store_type'].fillna('Unknown')

# Step 4: Convert opening_date to datetime
stores_clean['opening_date'] = pd.to_datetime(stores_clean['opening_date'], errors='coerce')

# Step 5: Remove duplicates
print(f"Before removing duplicates: {len(stores_clean)} rows")
stores_clean = stores_clean.drop_duplicates(subset=['store_id'], keep='first')
print(f"After removing duplicates: {len(stores_clean)} rows")

print("\ndim_stores cleaned!")
print(f"\nUnique regions now: {stores_clean['region'].unique()}")

Before removing duplicates: 52 rows
After removing duplicates: 49 rows

dim_stores cleaned!

Unique regions now: ['North' 'South' 'East' 'West' 'Central']

### 3.3 Clean dim_dates

In [38]:
# Create a copy for cleaning
dates_clean = dim_dates.copy()

# Step 1: Standardize date_id to YYYY-MM-DD format
dates_clean['date_id'] = pd.to_datetime(dates_clean['date_id'], errors='coerce')
dates_clean['date_id'] = dates_clean['date_id'].dt.strftime('%Y-%m-%d')

# Step 2: Standardize date_display
dates_clean['date_display'] = pd.to_datetime(dates_clean['date_display'], errors='coerce')
dates_clean['date_display'] = dates_clean['date_display'].dt.strftime('%Y-%m-%d')

# Step 3: Standardize quarter format (convert Q1, Q2 etc. to integers)
dates_clean['quarter'] = dates_clean['quarter'].astype(str).str.replace('Q', '').astype(int)

# Step 4: Standardize month_name to full names
month_mapping = {
    'Jan': 'January', 'Feb': 'February', 'Mar': 'March', 'Apr': 'April',
    'May': 'May', 'Jun': 'June', 'Jul': 'July', 'Aug': 'August',
    'Sep': 'September', 'Oct': 'October', 'Nov': 'November', 'Dec': 'December'
}
dates_clean['month_name'] = dates_clean['month_name'].replace(month_mapping)

print("dim_dates cleaned!")
print(f"\nSample data:")
dates_clean.head()

dim_dates cleaned!

Sample data:

,date_id,date_display,year,month,month_name,day,day_of_week,day_name,week_of_year,quarter,season,is_weekend,is_holiday,is_month_end
0,2023-01-01,2023-01-01,2023,1,January,1,6,Sunday,52,1,Winter,1,1,0
1,2023-01-02,NaN,2023,1,January,2,0,Monday,1,1,Winter,0,0,0
2,2023-01-03,2023-01-03,2023,1,January,3,1,Tuesday,1,1,Winter,0,0,0
3,2023-01-04,2023-01-04,2023,1,January,4,2,Wednesday,1,1,Winter,0,0,0
4,2023-01-05,2023-01-05,2023,1,January,5,3,Thursday,1,1,Winter,0,0,0

### 3.4 Clean dim_suppliers

In [39]:
# Create a copy for cleaning
suppliers_clean = dim_suppliers.copy()

# Step 1: Standardize supplier_id
suppliers_clean['supplier_id'] = suppliers_clean['supplier_id'].str.upper().str.strip()

# Step 2: Standardize active_status
active_mapping = {
    'active': 'Active', 'ACTIVE': 'Active', 'yes': 'Active', 'Yes': 'Active', 
    '1': 'Active', 1: 'Active', 'inactive': 'Inactive', 'INACTIVE': 'Inactive',
    'no': 'Inactive', 'No': 'Inactive', '0': 'Inactive', 0: 'Inactive'
}
suppliers_clean['active_status'] = suppliers_clean['active_status'].replace(active_mapping)

# Step 3: Handle missing values
suppliers_clean['contact_email'] = suppliers_clean['contact_email'].fillna('unknown@email.com')
suppliers_clean['phone'] = suppliers_clean['phone'].replace('N/A', np.nan)
suppliers_clean['phone'] = suppliers_clean['phone'].fillna('Not Available')
suppliers_clean['lead_time_days'] = suppliers_clean['lead_time_days'].fillna(
    suppliers_clean['lead_time_days'].median()
)
suppliers_clean['reliability_score'] = suppliers_clean['reliability_score'].fillna(
    suppliers_clean['reliability_score'].median()
)

print("dim_suppliers cleaned!")
print(f"\nActive status values: {suppliers_clean['active_status'].unique()}")
suppliers_clean.head()

dim_suppliers cleaned!

Active status values: ['Active']

,supplier_id,supplier_name,contact_email,phone,country,lead_time_days,reliability_score,min_order_quantity,payment_terms,active_status
0,S101,GLOBAL SUPPLIES CO,contact@globalsupp.com,+1-389-119-6965,Mexico,5.0,4.1,100,Net 60,Active
1,S102,FastTrack Logistics,contact@fasttrackl.com,+1-619-756-6276,China,24.0,4.1,25,Net 60,Active
2,S103,Prime Distributors,contact@primedistr.com,Not Available,Vietnam,19.0,4.2,10,Net 15,Active
3,S104,QUALITY FIRST INC,contact@qualityfir.com,+1-281-579-1994,Japan,16.0,4.6,10,NaN,Active
4,S105,Reliable Wholesale,contact@reliablewh.com,Not Available,Mexico,6.0,3.5,100,Net 60,Active

### 3.5 Clean fact_sales

In [40]:
# Create a copy for cleaning
sales_clean = fact_sales.copy()

# Step 1: Standardize IDs to uppercase
sales_clean['product_id'] = sales_clean['product_id'].str.upper().str.strip()
sales_clean['store_id'] = sales_clean['store_id'].str.upper().str.strip()

# Step 2: Standardize date_id format
sales_clean['date_id'] = pd.to_datetime(sales_clean['date_id'], errors='coerce')
sales_clean['date_id'] = sales_clean['date_id'].dt.strftime('%Y-%m-%d')

# Step 3: Handle missing values
print("Missing values before cleaning:")
print(sales_clean.isnull().sum())

# Fill numeric columns with median
numeric_cols = ['quantity_sold', 'unit_price', 'current_stock_level']
for col in numeric_cols:
    if col in sales_clean.columns:
        sales_clean[col] = sales_clean[col].fillna(sales_clean[col].median())

print("\nMissing values handled!")

Missing values before cleaning:
transaction_id            0
date_id                 965
product_id                0
store_id                  0
quantity_sold           896
unit_price             1425
gross_amount            955
discount_percentage       0
discount_amount           0
net_amount              965
is_promotion              0
current_stock_level    2218
reorder_point             0
units_to_stock            0
stockout_flag             0
dtype: int64

Missing values handled!

In [41]:
# Step 4: Handle outliers in quantity_sold using IQR method
print("Outlier Analysis for quantity_sold:")
print(f"Before - Min: {sales_clean['quantity_sold'].min()}, Max: {sales_clean['quantity_sold'].max()}")

Q1 = sales_clean['quantity_sold'].quantile(0.25)
Q3 = sales_clean['quantity_sold'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"IQR bounds: [{lower_bound:.2f}, {upper_bound:.2f}]")

# Count outliers
outliers = sales_clean[(sales_clean['quantity_sold'] < lower_bound) | 
                       (sales_clean['quantity_sold'] > upper_bound)]
print(f"Outliers found: {len(outliers)} ({len(outliers)/len(sales_clean)*100:.2f}%)")

# Cap outliers (clipping)
sales_clean['quantity_sold'] = sales_clean['quantity_sold'].clip(lower=0, upper=upper_bound)
print(f"After - Min: {sales_clean['quantity_sold'].min()}, Max: {sales_clean['quantity_sold'].max()}")

Outlier Analysis for quantity_sold:
Before - Min: 1.0, Max: 1000.0
IQR bounds: [-5.50, 14.50]
Outliers found: 3074 (6.49%)
After - Min: 1.0, Max: 14.5

In [42]:
# Step 5: Remove duplicate transactions
print(f"Before removing duplicates: {len(sales_clean)} rows")
sales_clean = sales_clean.drop_duplicates(subset=['transaction_id'], keep='first')
print(f"After removing duplicates: {len(sales_clean)} rows")

print("\n fact_sales cleaned!")

Before removing duplicates: 47371 rows
After removing duplicates: 47136 rows

 fact_sales cleaned!

---
## 4. Task 1.3: Data Integration

### 4.1 Join All Tables

In [43]:
# Start with fact_sales as base
print("Joining tables...")
print(f"\nBase table (fact_sales): {len(sales_clean)} rows")

# Join with dim_products
df_merged = sales_clean.merge(
    products_clean, 
    on='product_id', 
    how='left',
    suffixes=('', '_product')
)
print(f"After joining dim_products: {len(df_merged)} rows")

# Join with dim_stores
df_merged = df_merged.merge(
    stores_clean,
    on='store_id',
    how='left',
    suffixes=('', '_store')
)
print(f"After joining dim_stores: {len(df_merged)} rows")

# Join with dim_dates
df_merged = df_merged.merge(
    dates_clean,
    on='date_id',
    how='left',
    suffixes=('', '_date')
)
print(f"After joining dim_dates: {len(df_merged)} rows")

# Join with dim_suppliers (through products)
df_merged = df_merged.merge(
    suppliers_clean,
    on='supplier_id',
    how='left',
    suffixes=('', '_supplier')
)
print(f"After joining dim_suppliers: {len(df_merged)} rows")

Joining tables...

Base table (fact_sales): 47136 rows
After joining dim_products: 47136 rows
After joining dim_stores: 47136 rows
After joining dim_dates: 47136 rows
After joining dim_suppliers: 47136 rows

### 4.2 Validate Joins

In [44]:
print("=" * 60)
print("JOIN VALIDATION")
print("=" * 60)

# Check for row count consistency
original_rows = len(sales_clean)
merged_rows = len(df_merged)
print(f"\nRow Count Comparison:")
print(f"   Original fact_sales: {original_rows}")
print(f"   After all joins: {merged_rows}")
print(f"   Difference: {merged_rows - original_rows}")

# Check for null values from joins (unmatched keys)
print(f"\nUnmatched Keys (NaN from joins):")
key_columns = ['category', 'region', 'season', 'supplier_name']
for col in key_columns:
    if col in df_merged.columns:
        null_count = df_merged[col].isnull().sum()
        print(f"   {col}: {null_count} nulls ({null_count/len(df_merged)*100:.2f}%)")

============================================================
JOIN VALIDATION
============================================================

Row Count Comparison:
   Original fact_sales: 47136
   After all joins: 47136
   Difference: 0

Unmatched Keys (NaN from joins):
   category: 0 nulls (0.00%)
   region: 0 nulls (0.00%)
   season: 960 nulls (2.04%)
   supplier_name: 0 nulls (0.00%)

In [45]:
# Final data quality check
print("\nFinal Dataset Info:")
print(f"Shape: {df_merged.shape}")
print(f"\nColumns ({len(df_merged.columns)}):")
print(df_merged.columns.tolist())

Final Dataset Info:
Shape: (47136, 55)

Columns (55):
['transaction_id', 'date_id', 'product_id', 'store_id', 'quantity_sold', 'unit_price', 'gross_amount', 'discount_percentage', 'discount_amount', 'net_amount', 'is_promotion', 'current_stock_level', 'reorder_point', 'units_to_stock', 'stockout_flag', 'product_name', 'category', 'subcategory', 'unit_price_product', 'cost_price', 'supplier_id', 'shelf_life_days', 'weight_kg', 'is_perishable', 'store_name', 'store_type', 'city', 'region', 'store_size_sqft', 'opening_date', 'manager_id', 'num_employees', 'parking_capacity', 'date_display', 'year', 'month', 'month_name', 'day', 'day_of_week', 'day_name', 'week_of_year', 'quarter', 'season', 'is_weekend', 'is_holiday', 'is_month_end', 'supplier_name', 'contact_email', 'phone', 'country', 'lead_time_days', 'reliability_score', 'min_order_quantity', 'payment_terms', 'active_status']

In [46]:
# Display sample of merged data
print("\n Sample of Merged Dataset:")
df_merged.head()

 Sample of Merged Dataset:

,transaction_id,date_id,product_id,store_id,quantity_sold,unit_price,gross_amount,discount_percentage,discount_amount,net_amount,is_promotion,current_stock_level,reorder_point,units_to_stock,stockout_flag,product_name,category,subcategory,unit_price_product,cost_price,supplier_id,shelf_life_days,weight_kg,is_perishable,store_name,store_type,city,region,store_size_sqft,opening_date,manager_id,num_employees,parking_capacity,date_display,year,month,month_name,day,day_of_week,day_name,week_of_year,quarter,season,is_weekend,is_holiday,is_month_end,supplier_name,contact_email,phone,country,lead_time_days,reliability_score,min_order_quantity,payment_terms,active_status
0,T100001,2023-01-01,P1026,ST021,2.0,82.53,536.90,0,0.0,536.90,No,282.0,31,0,0,Accessories Item 2,Electronics,Accessories,268.45,124.59,S113,NaN,2.55,No,New York Supermarket #1,Supermarket,New York,East,4893,2020-09-01,M1013,58.0,134,2023-01-01,2023.0,1.0,January,1.0,6.0,Sunday,52.0,1.0,Winter,1.0,1.0,0.0,Alliance Distribution,contact@alliancedi.com,+1-849-896-7266,USA,4.0,4.1,50,NaN,Active
1,T100002,2023-01-01,P1191,ST011,1.0,86.06,86.06,0,0.0,86.06,No,190.0,65,0,0,Fragrances Item 7,Beauty,Fragrances,86.06,39.49,S118,90.0,4.61,No,Houston Hypermarket #2,Hypermarket,Houston,South,17598,2015-07-27,M1043,77.0,376,2023-01-01,2023.0,1.0,January,1.0,6.0,Sunday,52.0,1.0,Winter,1.0,1.0,0.0,First Choice Suppliers,unknown@email.com,+1-351-989-5713,USA,28.0,3.9,10,Net 15,Active
2,T100003,2023-01-01,P1143,ST018,4.0,236.75,947.00,0,0.0,947.00,No,469.0,70,0,0,Furniture Item 7,Home & Kitchen,Furniture,236.75,134.38,S112,NaN,7.54,No,New Orleans Supermarket #3,Supermarket,New Orleans,South,5164,2016-04-29,M1030,123.0,401,2023-01-01,2023.0,1.0,January,1.0,6.0,Sunday,52.0,1.0,Winter,1.0,1.0,0.0,Trusted Vendors Inc,contact@trustedven.com,+1-790-490-2285,USA,13.0,4.6,100,Net 30,Active
3,T100004,2023-01-01,P1110,ST020,14.5,19.37,387.40,0,0.0,387.40,No,287.0,36,0,0,Frozen Item 6,Groceries,Frozen,19.37,11.57,S109,NaN,10.32,Yes,New York Warehouse #4,Warehouse,New York,East,24158,2017-10-10,M1044,40.0,319,2023-01-01,2023.0,1.0,January,1.0,6.0,Sunday,52.0,1.0,Winter,1.0,1.0,0.0,Direct Source Inc,contact@directsour.com,Not Available,Mexico,13.0,4.1,500,Net 15,Active
4,T100005,2023-01-01,P1111,ST010,14.5,23.62,448.78,0,0.0,448.78,No,172.0,28,0,0,Frozen Item 7,Grocery,Frozen,23.62,15.85,S108,180.0,2.93,Yes,Indianapolis Hypermarket #2,Hypermarket,Indianapolis,North,16910,2018-11-19,M1029,142.0,159,2023-01-01,2023.0,1.0,January,1.0,6.0,Sunday,52.0,1.0,Winter,1.0,1.0,0.0,Value Chain Partners,contact@valuechain.com,+1-962-360-6898,Canada,15.0,4.1,10,Net 15,Active

### 4.3 Export Cleaned Dataset

In [47]:
# Export to CSV
output_path = 'cleaned_inventory_data.csv'
df_merged.to_csv(output_path, index=False)

print(f"Cleaned dataset exported to: {output_path}")
print(f"Final shape: {df_merged.shape}")
print(f"File size: {pd.read_csv(output_path).memory_usage(deep=True).sum() / 1024 / 1024:.2f} MB")

Cleaned dataset exported to: cleaned_inventory_data.csv
Final shape: (47136, 55)
File size: 77.51 MB

---
## 5. Summary

### Data Cleaning Completed:
-  Loaded all 5 CSV files
-  Fixed typos in categorical values
-  Standardized inconsistent casing
-  Handled missing values with appropriate strategies
-  Removed duplicate records
-  Converted date columns to proper format
-  Handled outliers using IQR method
-  Joined all dimension tables with fact table
-  Exported cleaned dataset to CSV

---
**Next Step:** Proceed to `02_eda.ipynb` for Exploratory Data Analysis